### ISSUE TITLE
Numpy deprecated and removed np.bool after version 1.23.5

### ISSUE THREAD

**Issue by cwalshai** [getspams/spams-python#27]
An error is thrown when trying to instantiate numpy arrays with the deprecated and removed numpy datatype np.bool. I think it should now be np.bool_ in spams-python/spams.py lines 1858 and 1834, and anywhere else the old np.bool is referenced.

Thank you for the help.

**Comment by samuelstjean** [comment]
Just using 'bool' should also be possible. I'm currently fixing the wrapper to unify it and that was also included, but for now it should just be a warning for version before 1.24

**Comment by cwalshai** [comment]
I have reverted back to 1.23.5 just now. Thanks for the help.

**Comment by diricxbart** [comment]
Will there be a new pypy release for this package? This issue really breaks this package.

The latest version I see is 2.6.5.4 and dates from April 2022, so I'm hoping for a new version...

**Comment by samuelstjean** [comment]
Well in the meantime my fork has the fix https://github.com/samuelstjean/spams-python and a few other things that are being tested out for inclusion here once we are sure it does not break anything.

**Comment by samuelstjean** [comment]
If I remember correctly, latest numpy broke the searching mechanism or something else we used in the setup.py, so that's why a simple change was not enough, and my fork hardcodes so much things for the binary builds to work easily that I could get away with it, but we need to update a few things here to do things properly for the long run.

**Comment by daducci** [comment]
I would suggest sticking with only one version, i.e. this one,  without proliferation of multiple custom versions.

**Comment by diricxbart** [comment]
I'm currently using the spams trainDL and lasso functions. This previously has been working just fine using numpy version 1.21.1, but fails when using numpy version 1.24.2.

For now I added the following into our Dockerfile after installation of the spams package:
```
RUN sudo sed -i 's/np.bool/"bool"/g' /usr/local/lib/python3.8/dist-packages/spams/spams.py
```
to workaround this breaking numpy np.bool deprecation issue. The goal is to remove this again from the Dockerfile once this issue is solved inside the spams package and just bump the spams version...

@samuelstjean Related to "latest numpy broke the searching mechanism or something else we used in the setup.py": is it correct that when spams successfully installs through pip, which it currently does in our Docker image and after applying the above workaround, that I should be good to go? There are no functional breaking changes (affecting the algorithms / results)?

**Comment by samuelstjean** [comment]
indeed, the problem is that we rely on some lazy workaround to detect the blas libs at build time, and the whole thing is going away in numpy.distutils (in particular I think some submodule we are using got removed in 1.24, it may have been fixed since I just packaged it myself here). So once you have a built version, then everything is fine.
